# Generated by Django 5.2.4 on 2025-07-23 16:50

import User.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', User.models.UserManager()),
            ],
        ),
    ]
